# Copyright (c) 2026, Viv Choudhary and contributors
# For license information, please see license.txt

import frappe


def execute(filters=None):

	filters = filters or {}

	# --------------------------------
	# Conditions
	# --------------------------------

	where_clauses = ["docstatus < 2"]
	params = {}

	if filters.get("company"):
	    where_clauses.append("company = %(company)s")
	    params["company"] = filters["company"]

	if filters.get("from_date"):
	    where_clauses.append("posting_date >= %(from_date)s")
	    params["from_date"] = filters["from_date"]

	if filters.get("to_date"):
	    where_clauses.append("posting_date <= %(to_date)s")
	    params["to_date"] = filters["to_date"]

	where_sql = " AND ".join(where_clauses)

	# --------------------------------
	# Query
	# --------------------------------

	query = f"""

	SELECT

	    owner,
	    posting_date

	FROM `tabProduction Plan`

	WHERE {where_sql}

	ORDER BY owner, posting_date

	"""

	result = frappe.db.sql(query, params, as_dict=True)

	# --------------------------------
	# Month Mapping
	# --------------------------------

	month_map = {
	    4: "apr",
	    5: "may",
	    6: "jun",
	    7: "jul",
	    8: "aug",
	    9: "sep",
	    10: "oct",
	    11: "nov",
	    12: "dec",
	    1: "jan",
	    2: "feb",
	    3: "mar",
	}

	months = [
	    "apr","may","jun","jul","aug","sep",
	    "oct","nov","dec","jan","feb","mar"
	]

	# --------------------------------
	# Build User Rows
	# --------------------------------

	rows = {}

	for d in result:

	    user = frappe.db.get_value(
	        "User",
	        d.owner,
	        "full_name"
	    ) or d.owner

	    if user not in rows:

	        rows[user] = {
	            "user": user
	        }

	        for m in months:
	            rows[user][m] = 0

	    month = month_map.get(d.posting_date.month)

	    rows[user][month] = rows[user][month] + 1

	# --------------------------------
	# Prepare Report Data
	# --------------------------------

	report_data = []

	monthly_total = {
	    "user": "Monthly Total Qty"
	}

	for m in months:
	    monthly_total[m] = 0

	grand_total = 0

	for row in sorted(rows.values(), key=lambda x: x["user"]):

	    total = 0

	    for m in months:

	        total = total + row[m]

	        monthly_total[m] = monthly_total[m] + row[m]

	    row["year_total"] = total

	    grand_total = grand_total + total

	    report_data.append(row)

	monthly_total["year_total"] = grand_total

	report_data.append(monthly_total)

	# --------------------------------
	# Columns
	# --------------------------------

	columns = [

	    {
	        "label":"Generated By",
	        "fieldname":"user",
	        "fieldtype":"Data",
	        "width":180
	    },

	    {
	        "label":"April",
	        "fieldname":"apr",
	        "fieldtype":"Int",
	        "width":70
	    },

	    {
	        "label":"May",
	        "fieldname":"may",
	        "fieldtype":"Int",
	        "width":70
	    },

	    {
	        "label":"June",
	        "fieldname":"jun",
	        "fieldtype":"Int",
	        "width":70
	    },

	    {
	        "label":"July",
	        "fieldname":"jul",
	        "fieldtype":"Int",
	        "width":70
	    },

	    {
	        "label":"August",
	        "fieldname":"aug",
	        "fieldtype":"Int",
	        "width":70
	    },

	    {
	        "label":"September",
	        "fieldname":"sep",
	        "fieldtype":"Int",
	        "width":80
	    },

	    {
	        "label":"October",
	        "fieldname":"oct",
	        "fieldtype":"Int",
	        "width":70
	    },

	    {
	        "label":"November",
	        "fieldname":"nov",
	        "fieldtype":"Int",
	        "width":80
	    },

	    {
	        "label":"December",
	        "fieldname":"dec",
	        "fieldtype":"Int",
	        "width":80
	    },

	    {
	        "label":"January",
	        "fieldname":"jan",
	        "fieldtype":"Int",
	        "width":70
	    },

	    {
	        "label":"February",
	        "fieldname":"feb",
	        "fieldtype":"Int",
	        "width":80
	    },

	    {
	        "label":"March",
	        "fieldname":"mar",
	        "fieldtype":"Int",
	        "width":70
	    },

	    {
	        "label":"Yearly Total",
	        "fieldname":"year_total",
	        "fieldtype":"Int",
	        "width":120
	    }

	]

	# --------------------------------
	# Summary
	# --------------------------------

	summary = [

	    {
	        "value": len(rows),
	        "label": "Total Users",
	        "datatype": "Int"
	    },

	    {
	        "value": grand_total,
	        "label": "Total Work Orders",
	        "datatype": "Int"
	    }

	]

	# --------------------------------
	# Return
	# --------------------------------

	return columns, report_data, None, None, summary
